---
- name: Deploy Morpheus Instance
  hosts: all
  gather_facts: false

  vars:
    morpheus_url: "https://morpheus.ocp4.office.igotit.co.kr"
    api_token: "ab8a74fc-4589-4d63-8594-a2841c336c47" # 보안을 위해 나중에는 vault 사용 권장

  tasks:
    - name: Create instance via Morpheus API
      ansible.builtin.uri:
        url: "{{ morpheus_url }}/api/instances"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        validate_certs: false  # curl -k와 동일한 효과
        body:
          zoneId: 9
          instance:
            name: "cham-test"
            cloud: "hvm"
            site:
              id: 1
            type: "ubuntu"
            instanceType:
              code: "ubuntu"
            instanceContext: "dev"
            labels:
              - "hvm-server"
            layout:
              id: 215
            plan:
              id: 248
            userGroup:
              id: 1
          config:
            resourcePoolId: "pool-341"
            maxMemory: 4294967296
            createUser: true
          volumes:
            - id: -1
              rootVolume: true
              name: "root"
              size: 100
              storageType: 1
              datastoreId: "34"
          networkInterfaces:
            - network:
                id: "network-14"
              networkInterfaceTypeId: 10
              ipMode: "static"
              ipAddress: "192.168.40.181"
          layoutSize: 1
          copies: 1
          servicePlanOptions:
            coresPerSocket: 1
            maxCores: 2
      register: api_response

    - name: Print result
      ansible.builtin.debug:
        var: api_response.json
