---
- name: Morpheus Provisioning via AWX
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Request New VMware Instance to Morpheus
      ansible.builtin.uri:
        url: "https://morpheus.ocp4.office.igotit.co.kr/api/instances"
        method: POST
        validate_certs: false 
        status_code: [200, 201]
        headers:
          accept: "application/json"
          authorization: "Bearer ab8a74fc-4589-4d63-8594-a2841c336c47"
          content-type: "application/json"
        body_format: json
        body:
          zoneId: 10
          instance:
            name: "vmware-cham-test"          
            cloud: "vmware"
            site:
              id: 1
            type: "ubuntu"
            instanceType:
              code: "ubuntu"
            instanceContext: "dev"
            labels: ["vmware-cham-server"]    
            layout:
              id: 212
            plan:
              id: 247
          config:
            resourcePoolId: "pool-339"
            maxMemory: 8589934592
            createUser: false
          volumes:
            - id: -1
              rootVolume: true
              name: "root"
              size: 100
              storageType: 1
              datastoreId: "31"
          networkInterfaces:
            - network:
                id: "network-8"
              ipMode: "static"
              ipAddress: "192.168.40.195"
          layoutSize: 1
          copies: 1
          labels: ["vmware-cham-server"]      
          servicePlanOptions:
            coresPerSocket: 1
            maxCores: 4
      register: morpheus_response

    - name: Print Response
      ansible.builtin.debug:
        var: morpheus_response.json
